// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayConstants
{
	/*
        public const string achievement_enter_the_game_20_times = "CgkI-K6jy4kWEAIQBA"; // <GPGSID>
        public const string achievement_collect_1000_planets = "CgkI-K6jy4kWEAIQAw"; // <GPGSID>
        public const string achievement_share_your_planet_system_with_a_friend = "CgkI-K6jy4kWEAIQBQ"; // <GPGSID>
        public const string achievement_collect_100_planets_in_one_shot = "CgkI-K6jy4kWEAIQAg"; // <GPGSID>
        public const string leaderboard_total_number_of_planets = "CgkI-K6jy4kWEAIQCA"; // <GPGSID>
        public const string achievement_collect_100_planets_in_one_shot_without_missing_one = "CgkI-K6jy4kWEAIQBg"; // <GPGSID>
    */
        public const string leaderboard_best_starters = "CgkI-K6jy4kWEAIQBw"; // <GPGSID>

		public const string marketURL = "market://details?id=com.cosmicgardenlabs.supernova";

}

